package templates

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
	"text/template"
)

// WordPressConfig holds WordPress configuration.
type WordPressConfig struct {
	DBName      string
	DBUser      string
	DBPassword  string
	DBHost      string
	TablePrefix string
	Debug       bool

	// Generated keys and salts.
	AuthKey        string
	SecureAuthKey  string
	LoggedInKey    string
	NonceKey       string
	AuthSalt       string
	SecureAuthSalt string
	LoggedInSalt   string
	NonceSalt      string
}

const wpConfigTemplate = `<?php
/**
 * WordPress Configuration - Generated by LiteCP
 */

// Database settings
define( 'DB_NAME', '{{php .DBName}}' );
define( 'DB_USER', '{{php .DBUser}}' );
define( 'DB_PASSWORD', '{{php .DBPassword}}' );
define( 'DB_HOST', '{{php .DBHost}}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

// Authentication keys and salts
define( 'AUTH_KEY',         '{{php .AuthKey}}' );
define( 'SECURE_AUTH_KEY',  '{{php .SecureAuthKey}}' );
define( 'LOGGED_IN_KEY',    '{{php .LoggedInKey}}' );
define( 'NONCE_KEY',        '{{php .NonceKey}}' );
define( 'AUTH_SALT',        '{{php .AuthSalt}}' );
define( 'SECURE_AUTH_SALT', '{{php .SecureAuthSalt}}' );
define( 'LOGGED_IN_SALT',   '{{php .LoggedInSalt}}' );
define( 'NONCE_SALT',       '{{php .NonceSalt}}' );

// Database table prefix
$table_prefix = '{{php .TablePrefix}}';

// Security
define( 'DISALLOW_FILE_EDIT', true );
define( 'FORCE_SSL_ADMIN', true );

// Performance
define( 'WP_MEMORY_LIMIT', '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '512M' );

// HTTPS and SSL handling behind Caddy/reverse proxies
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
	$_SERVER['HTTPS'] = 'on';
}
if ( isset( $_SERVER['HTTP_X_FORWARDED_SSL'] ) && $_SERVER['HTTP_X_FORWARDED_SSL'] === 'on' ) {
	$_SERVER['HTTPS'] = 'on';
}

if ( isset( $_SERVER['HTTPS'] ) && $_SERVER['HTTPS'] === 'on' ) {
	define( 'WP_HOME', 'https://' . $_SERVER['HTTP_HOST'] );
	define( 'WP_SITEURL', 'https://' . $_SERVER['HTTP_HOST'] );
}

// Debugging
define( 'WP_DEBUG', {{bool .Debug}} );
{{if .Debug}}define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
{{end}}

// Absolute path to WordPress directory
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

// Load WordPress
require_once ABSPATH . 'wp-settings.php';
`

// GenerateWPConfig generates a wp-config.php file.
func GenerateWPConfig(config *WordPressConfig) (string, error) {
	if config == nil {
		return "", fmt.Errorf("wordpress config is nil")
	}

	if err := fillWPSecrets(config); err != nil {
		return "", err
	}
	if config.DBHost == "" {
		config.DBHost = "127.0.0.1"
	}
	if config.TablePrefix == "" {
		config.TablePrefix = "wp_"
	}

	funcMap := template.FuncMap{
		"php":  phpSingleQuotedString,
		"bool": boolLiteral,
	}
	tmpl, err := template.New("wp-config").Funcs(funcMap).Parse(wpConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}
	return buf.String(), nil
}

func fillWPSecrets(config *WordPressConfig) error {
	secretFields := []*string{
		&config.AuthKey,
		&config.SecureAuthKey,
		&config.LoggedInKey,
		&config.NonceKey,
		&config.AuthSalt,
		&config.SecureAuthSalt,
		&config.LoggedInSalt,
		&config.NonceSalt,
	}
	for _, field := range secretFields {
		if *field != "" {
			continue
		}
		key, err := generateWPKey()
		if err != nil {
			return err
		}
		*field = key
	}
	return nil
}

func phpSingleQuotedString(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `'`, `\'`)
	return value
}

func boolLiteral(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func generateWPKey() (string, error) {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("failed to generate WordPress key: %w", err)
	}
	return hex.EncodeToString(bytes), nil
}
